### ISSUE TITLE
Dev system-unique hard-coded db.json location causing runtime error in view-pt.py

### ISSUE THREAD

**Issue by therden** [dagraham/etm-mvc#2]
Attempting to run view-pt.py as is from etm-mvc repo results in following error:

> Traceback (most recent call last):
>   File "view-pt.py", line 21, in <module>
>     from model import str2item, at_regex, amp_regex, type_keys, methods, requirements, at_keys, amp_keys 
> ......
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/dag/etm-sandbox/etm-web/db.json'
> 

If line 145 of model.py is edited to point to a valid path, for example

`def get_config(dbfile='db.json'):`

then a skeleton config/data file will created in the root of application directory and the prototype will run fine.

**Comment by dagraham** [comment]
Thomas,

Thanks, but I’m not really trying to make view-pt.py work on users platforms. I doubt it will be the view actually used and am currently working on another.

-Dan

On Jul 24, 2016, at 3:14 PM, therden <notifications@github.com<mailto:notifications@github.com>> wrote:


Attempting to run view-pt.py as is from etm-mvc repo results in following error:

Traceback (most recent call last):
File "view-pt.py", line 21, in
from model import str2item, at_regex, amp_regex, type_keys, methods, requirements, at_keys, amp_keys
......
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dag/etm-sandbox/etm-web/db.json'

If line 145 of model.py is edited to point to a valid path, for example

def get_config(dbfile='db.json'):

then a skeleton config/data file will created in the root of application directory and the prototype will run fine.

**Comment by therden** [comment]
Oh, okay.  I'd supposed otherwise because you'd posted an invitation to to run it to the Google Groups list.  No worries here...
